# Generated by Django 3.1.5 on 2021-05-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='explore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, choices=[('Array', 'Array'), ('Matrix', 'Matrix'), ('String', 'String'), ('Searching & Sorting', 'Searching & Sorting'), ('LinkedList', 'LinkedList'), ('Binary Trees', 'Binary Trees'), ('Binary Search Trees', 'Binary Search Trees'), ('Greedy', 'Greedy'), ('BackTracking', 'BackTracking'), ('Stacks & Queues', 'Stacks & Queues'), ('Heap', 'Heap'), ('Graph', 'Graph'), ('Trie', 'Trie'), ('Dynamic Programming', 'Dynamic Programming'), ('Bit Manipulation', 'Bit Manipulation')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=32)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
