# Generated by Django 3.1.5 on 2021-05-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='explore',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
